### ISSUE TITLE
EiffelArtifactDeployedEvent should reference composition

### ISSUE THREAD

**Issue by l-ohlen-ericsson** [Ericsson/eiffel-operations-extension#35]
The EiffelArtifactDeployedEvent must be able to refer to more than 1 artifact.
The solution is to use a composition link

**Comment by erobged** [comment]
@l-ohlen-ericsson  to make the changes in github prior to closing this issue

**Comment by d-stahl-ericsson** [comment]
The more I think about it, the more I question using compositions here. An event should represent an atomic event, not a cluster of related things. In ArtifactCreated, CompositionDefined is used because it's a re-usable one-to-many relationship represented by one event per occurrence.

Introducing the need for CompositionDefined to report deployment strikes me as messy, because then you're using a CompositionDeployed event to represent a number of deployments that occurred over some unknown period of time. So even if multiple deployments as part of a single service is a common scenario, sending multiple ArtifactDeployed would be cleaner, simpler and more expressive than sending a single CompositionDefined.

If you want to keep multiple artifact deployments grouped together, it would make sense to represent deployments as something that occurs over a period of time, similar to TestCase*, Activity* and TestSuite* events. In other words, e.g.:
```
ServiceDeploymentStarted <- ServiceDeploymentFinished
                         <- ArtifactDeployed
                         <- ArtifactDeployed
                         <- ArtifactDeployed
```

This would also increase the expressive power of the events, rather than diminish it.

**Comment by erobged** [comment]
Resolved and Pull Request completed.
