### ISSUE TITLE
SERVICE links missing

### ISSUE THREAD

**Issue by d-stahl-ericsson** [Ericsson/eiffel-operations-extension#39]
I would expect Service* events to feature SERVICE links identifying some provenance event, so that a unique service can be idenfitied and its lifecycle easily traced.

**Comment by erobged** [comment]
pulling in others to discuss this idea @ebopalm  @l-ohlen-ericsson .

Lars you've mentioned a CompositionDefinedEvent for building up Service structures.
Re: [Ericsson/eiffel-operations-extension] Adjustment for #35 (#36)

How would this SERVICE link fit or is it something else altogether that could be used ?

**Comment by erobged** [comment]
@d-stahl-ericsson 
Could you give me an example please of  what you think would be the provenance event ? (maybe it is a ServiceDeployedEvent ?)

**Comment by d-stahl-ericsson** [comment]
I should ask you that :)
It's not completely clear to me how the events relate to one another exactly, largely because there are no links representing those relationships. So for me trying to suggest what might be a suitable event would be somewhat circular... That being said, it needs to be something that occurs first in time, since you can only point backwards in time. If there is no obvious candidate, perhaps a dedicated event is appropriate (we have other *DefinedEvent in the vocabulary).

**Comment by erobged** [comment]
An example of the thinking here is in a Cloud context. we layer Services on top of another building up a structure. for example BaaS, IaaS, SaaS etc.... physical , virtual , software layer.
However , this just my interpretation of a single scenario.
you could use these events to provide traceability of order/timing in which specific Services are started in an Ericsson Product.

**Comment by d-stahl-ericsson** [comment]
All the more reason to identify a clear service provenance event, because you probably want to be able to model that hierarchy, should you wish to. Should there actually be e.g. an optional ENCAPSULATING_SERVICE link as well? For instance,
EiffelServiceDeployedEvent (IaaS) <-- ENCAPSULATING_SERVICE -- EiffelServiceDeployedEvent (SaaS)

Please note that I'm just spouting random thoughts. I'm looking at you as the deep thinker here.

**Comment by rogpers-ericsson** [comment]
Defining a defining event, similar to ArtC, makes sense.

The graph of services are in some sense similar to an artifact aggregation graph, but also quite different in other senses, e.g. in the temporal dimension.

Having a well defined "start" would be good.

**Comment by erobged** [comment]
@ebopalm , suggestions ?

**Comment by erobged** [comment]
Bo would like to add events that captures the relationship between Services as we are assuming a model based on tree structure of recursive/layered service where services are build on services. The purpose of these events are to facilitate the building of the inventory database and representing the layered service model. Two events are needed to handle relationships:

ServiceRelationshipCreated
ServiceRelationshipRemoved 
The events should define:

the type of relationship (Containment or Connetion)

possible sub type of relationship (not yet investigated)
reference to the originating service
references to relating service
Contraints: 

A reference only involves two services to ease building service object models (assumed to use EI for that) and updating the service tree.

References are singularities and points downwards in the service tree. As such traversing the tree upwards using events is not possible. A service tree object model is needed.

Unless other data is to be maintained by these events, there are likely no need for a ServiceRelationshipUpdated event. 

Comments ?

**Comment by d-stahl-ericsson** [comment]
My intuition is that relationships are best captured by references, not by events. See my suggestion above regarding the introduction of e.g. ENCAPSULATING_SERVICE as a link type. If there's a need for multiple types of relationships, then multiple link types can be created accordingly (e.g. CONNECTED_SERVICE), as long as they are clearly defined, documented and separated.

**Comment by ebopalm** [comment]
The original suggestion to have relationship as events was based on the fact that it was not flexible enugh to tie the relationship definition to another event e.g. "ServiceDeployed". The reason is that a relationship lifecycle should be independent on the lifecycle of the objects they refer to. This means that one can create a relationship during any stage of referring objects lifecycle. A few examples:
* An item-to-item relationship is defined as part of a static product structure.
* Two items are related at the time of instansiation as blueprinted by the defined prooduct structure.
* Two items are related and unrelated during a change/upgrade of one of the items in production.

Another reason for using event based relationship is the existence of "_EiffelCompositionDefinedEvent_". This event is infact a generic "Containment" definition. What is needed to complete the building of generic relationships with events is a "Connection" type event.
As they are generic in context, i suggest that CO (and others) uses _CompositionDefined_ as Containment" and we add new generic events (suggestion: _EiffelConnectionDefined_ & _EiffelConnectionUndefined_) to satisfy this use case.
These ideas are inspired by the TOSCA documentation where product/service structures were based upon these two relationship types.

**Comment by erobged** [comment]
assigned to Bo.

**Comment by d-stahl-ericsson** [comment]
It would be valuable with worked examples of how this would be used in practice. Alignment with TOSCA is of course neat, but we need to get a lot more tangible here.

In my mind, representing relationships with events only really make sense in cases of re-usable one-to-many relationships, as in the case of compositions. I'm not sure that is the case here? But again, concrete examples would probably help demonstrate this.

**Comment by erobged** [comment]
SERVICE link type defined... pull request completed.
